SET NAMES utf8mb4;

UPDATE customers SET billing_city='台中市',billing_district='新社區',billing_address='台中市新社區中和街一段84巷50號' WHERE customer_no='A-017105';
UPDATE customers SET billing_city='台中市',billing_district='潭子區',billing_address='台中市潭子區大新路75巷10號2樓之3' WHERE customer_no='A-017106';
UPDATE customers SET billing_city='台中市',billing_district='西屯區',billing_address='台中市西屯區工業區三十五路5號' WHERE customer_no='A-017108';
UPDATE customers SET billing_city='台中市',billing_district='神岡區',billing_address='台中市神岡區前寮路38號' WHERE customer_no='A-017126';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區嶺東路95巷12號' WHERE customer_no='A-017136';
UPDATE customers SET billing_city='台中市',billing_district='烏日區',billing_address='台中市烏日區學田路308號' WHERE customer_no='A-017137';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區向上路一段626號' WHERE customer_no='A-017149';
UPDATE customers SET billing_city='彰化縣',billing_district='線西鄉',billing_address='彰化縣線西鄉彰濱西五路2號' WHERE customer_no='A-017156';
UPDATE customers SET billing_city='彰化縣',billing_district='大村鄉',billing_address='彰化縣大村鄉中山路二段333號' WHERE customer_no='A-017159';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區工業二十五路18' WHERE customer_no='A-017160';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區工業二十五路18' WHERE customer_no='A-017161';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區工業二十五路18' WHERE customer_no='A-017162';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區工業二十五路18' WHERE customer_no='A-017163';
UPDATE customers SET billing_city='台中市',billing_district='南屯區',billing_address='台中市南屯區工業二十五路18' WHERE customer_no='A-017164';
UPDATE customers SET billing_city='高雄市',billing_district='鳥松區',billing_address='高雄市鳥松區本館路316號' WHERE customer_no='A-017165';
UPDATE customers SET billing_city='台中市',billing_address='台中市西區臺灣大道二段285號4樓之1' WHERE customer_no='A-017166';
UPDATE customers SET billing_city='南投縣',billing_district='草屯鎮',billing_address='南投縣草屯鎮永安路872號' WHERE customer_no='A-017171';
UPDATE customers SET billing_city='南投縣',billing_district='名間鄉',billing_address='南投縣名間鄉萬丹村山腳巷74-1號' WHERE customer_no='A-017177';
UPDATE customers SET billing_city='台北市',billing_district='內湖區',billing_address='台北市內湖區瑞光路502號4F  黃月沼小姐收' WHERE customer_no='A-017179';
UPDATE customers SET billing_city='台北市',billing_district='內湖區',billing_address='台北市內湖區瑞光路502號4F  黃月沼小姐收' WHERE customer_no='A-017180';
UPDATE customers SET billing_city='彰化縣',billing_district='鹿港鎮',billing_address='彰化縣鹿港鎮工業西七路1-39號' WHERE customer_no='A-017189';
