-- 修正 41 筆含 4-byte UTF8 字元的記錄
SET NAMES utf8mb4;

UPDATE customers SET name = '豐𪝞企業(股)公司蚵寮廠(2廠)' WHERE customer_no = 'A-001832';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-001833';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-002197';
UPDATE customers SET name = '豐𪝞企業(股)公司蚵寮廠(2廠)' WHERE customer_no = 'A-002465';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-003571';
UPDATE customers SET name = '豐𪝞企業(股)公司蚵寮廠(2廠)' WHERE customer_no = 'A-004447';
UPDATE customers SET name = '豐𪝞企業(股)公司蚵寮廠(2廠)' WHERE customer_no = 'A-004448';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-004465';
UPDATE customers SET name = '蔡佩宜 - 豐𪝞企業股份有限公司' WHERE customer_no = 'A-004927';
UPDATE customers SET name = '蔡佩宜 - 豐𪝞企業股份有限公司' WHERE customer_no = 'A-004928';
UPDATE customers SET name = '豐𪝞企業(股)公司蚵寮廠' WHERE customer_no = 'A-004974';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-005456';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-006645';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-006995';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-007086';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-007492';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-007529';
UPDATE customers SET name = '蔡佩宜 - 豐𪝞企業股份有限公司' WHERE customer_no = 'A-007683';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-007985';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-008157';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-009044';
UPDATE customers SET name = '吳國𨛦' WHERE customer_no = 'A-009436';
UPDATE customers SET contact_person = '吳國𨛦' WHERE customer_no = 'A-009436';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-009874';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-010370';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-010512';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-010811';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-010887';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-011212';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-011219';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-011895';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-012137';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-012243';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-012553';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-013722';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-014632';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-015196';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-015198';
UPDATE customers SET name = '豐𪝞企業(股)公司-西濱廠' WHERE customer_no = 'A-015946';
UPDATE customers SET name = '豐𪝞企業(股)公司-蚵寮廠' WHERE customer_no = 'A-016110';
UPDATE customers SET name = '豐𪝞企業(股)公司西濱廠(1廠)' WHERE customer_no = 'A-016375';
