-- Import: requisitions (headers only)
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260310-001', '2026-03-10', '黃星晴', 2, '許進鑫', '一般件', '西門子', NULL, '力梭', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260306-001', '2026-03-06', '黃星晴', 1, '陳宏璇', '一般件', '豐益 蚵寮', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260304-001', '2026-03-04', '蕭竹芸', 3, '謝旻倫', '急件', '瑞曼', NULL, NULL, NULL, '簽核中', NULL, NULL, NULL, '黃星晴', NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260303-003', '2026-03-03', '黃星晴', 1, '陳宏璇', '急件', '晨邑', NULL, '凱文', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260303-002', '2026-03-03', '黃星晴', 2, '許進鑫', '一般件', '西門子', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260303-001', '2026-03-03', '黃星晴', 1, '劉佳琦', '一般件', '頻威智科技', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260302-001', '2026-03-02', '黃星晴', 6, '許進鑫', '一般件', '西門子歌美颯', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-006', '2026-02-26', '蕭竹芸', 3, '謝旻倫', '急件', '瑞曼', NULL, NULL, '2026-03-03', '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-005', '2026-02-26', '黃星晴', 1, '陳宏璇', '一般件', '晨邑', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-004', '2026-02-26', '黃星晴', 6, '許進鑫', '一般件', '巨菱', NULL, '群洲', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-003', '2026-02-26', '黃星晴', 1, NULL, '一般件', '庫存', NULL, '俋安', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-002', '2026-02-26', '黃星晴', 1, '詹佳航', '一般件', '星星精油(西屯店)', NULL, '順喜', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260226-001', '2026-02-26', '顏伸祐', 2, '顏伸祐', '一般件', '益可達科技股份有限公司', NULL, '皇昇', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260225-002', '2026-02-25', '黃星晴', 1, '陳宏璇', '急件', '巨菱', NULL, '精誠', NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
INSERT INTO requisitions (requisition_number, requisition_date, requester_name, branch_id, sales_name, urgency, case_name, quotation_number, vendor_name, expected_date, status, approval_user, approval_date, approval_note, next_approver, note) VALUES ('PR-20260225-001', '2026-02-25', '鄭姵緁', 2, '顏伸祐', '一般件', '陳建竹', NULL, NULL, NULL, '簽核完成', NULL, NULL, NULL, NULL, NULL);
