-- Migration 026: 銀行帳戶、零用金、備用金、現金明細

-- 1. 銀行帳戶交易明細
CREATE TABLE IF NOT EXISTS bank_transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sys_number VARCHAR(30) DEFAULT NULL,
  upload_number VARCHAR(30) DEFAULT NULL,
  bank_account VARCHAR(100) DEFAULT NULL,
  transaction_date DATE DEFAULT NULL,
  posting_date DATE DEFAULT NULL,
  transaction_time VARCHAR(20) DEFAULT NULL,
  cash_transfer VARCHAR(10) DEFAULT NULL,
  summary VARCHAR(100) DEFAULT NULL,
  currency VARCHAR(10) DEFAULT 'TWD',
  debit_amount DECIMAL(12,0) DEFAULT 0,
  credit_amount DECIMAL(12,0) DEFAULT 0,
  balance DECIMAL(12,0) DEFAULT 0,
  note VARCHAR(200) DEFAULT NULL,
  transfer_account VARCHAR(50) DEFAULT NULL,
  bank_code VARCHAR(50) DEFAULT NULL,
  counter_account VARCHAR(50) DEFAULT NULL,
  remark VARCHAR(200) DEFAULT NULL,
  description VARCHAR(200) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. 零用金管理
CREATE TABLE IF NOT EXISTS petty_cash (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entry_number VARCHAR(30) DEFAULT NULL,
  entry_date DATE DEFAULT NULL,
  expense_date DATE DEFAULT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  type VARCHAR(10) DEFAULT '支出',
  has_invoice VARCHAR(10) DEFAULT '無發票',
  invoice_info VARCHAR(100) DEFAULT NULL,
  expense_untaxed DECIMAL(12,0) DEFAULT 0,
  expense_tax DECIMAL(12,0) DEFAULT 0,
  expense_amount DECIMAL(12,0) DEFAULT 0,
  income_amount DECIMAL(12,0) DEFAULT 0,
  description VARCHAR(200) DEFAULT NULL,
  registrar VARCHAR(50) DEFAULT NULL,
  approval_status VARCHAR(20) DEFAULT NULL,
  approval_date DATE DEFAULT NULL,
  user_name VARCHAR(50) DEFAULT NULL,
  upload_number VARCHAR(30) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. 備用金管理
CREATE TABLE IF NOT EXISTS reserve_fund (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entry_number VARCHAR(30) DEFAULT NULL,
  entry_date DATE DEFAULT NULL,
  expense_date DATE DEFAULT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  type VARCHAR(10) DEFAULT '支出',
  expense_amount DECIMAL(12,0) DEFAULT 0,
  income_amount DECIMAL(12,0) DEFAULT 0,
  description VARCHAR(200) DEFAULT NULL,
  invoice_info VARCHAR(100) DEFAULT NULL,
  registrar VARCHAR(50) DEFAULT NULL,
  approval_status VARCHAR(20) DEFAULT NULL,
  approval_date DATE DEFAULT NULL,
  user_name VARCHAR(50) DEFAULT NULL,
  upload_number VARCHAR(30) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. 現金明細
CREATE TABLE IF NOT EXISTS cash_details (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entry_number VARCHAR(30) DEFAULT NULL,
  register_date DATE DEFAULT NULL,
  transaction_date DATE DEFAULT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  sales_name VARCHAR(50) DEFAULT NULL,
  description VARCHAR(200) DEFAULT NULL,
  income_amount DECIMAL(12,0) DEFAULT 0,
  expense_amount DECIMAL(12,0) DEFAULT 0,
  upload_number VARCHAR(30) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
