-- Migration 025: 財務會計模組
-- 應收帳款、收款單、應付帳款單、付款單

-- 1. 應收帳款
CREATE TABLE IF NOT EXISTS receivables (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(30) NOT NULL,
  invoice_date DATE NOT NULL,
  case_id INT UNSIGNED DEFAULT NULL,
  customer_name VARCHAR(100) DEFAULT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  sales_id INT UNSIGNED DEFAULT NULL,
  invoice_category VARCHAR(50) DEFAULT NULL,
  status VARCHAR(20) DEFAULT '待請款',
  invoice_title VARCHAR(100) DEFAULT NULL,
  tax_id VARCHAR(20) DEFAULT NULL,
  phone VARCHAR(30) DEFAULT NULL,
  mobile VARCHAR(30) DEFAULT NULL,
  invoice_email VARCHAR(100) DEFAULT NULL,
  invoice_address VARCHAR(200) DEFAULT NULL,
  payment_method VARCHAR(30) DEFAULT NULL,
  payment_terms VARCHAR(50) DEFAULT NULL,
  subtotal DECIMAL(12,0) DEFAULT 0,
  note TEXT,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. 應收帳款-合併請款明細
CREATE TABLE IF NOT EXISTS receivable_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  receivable_id INT UNSIGNED NOT NULL,
  main_case_number VARCHAR(30) DEFAULT NULL,
  merge_case_number VARCHAR(30) DEFAULT NULL,
  amount DECIMAL(12,0) DEFAULT 0,
  note VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. 收款單
CREATE TABLE IF NOT EXISTS receipts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  receipt_number VARCHAR(30) NOT NULL,
  register_date DATE NOT NULL,
  deposit_date DATE DEFAULT NULL,
  customer_name VARCHAR(100) DEFAULT NULL,
  receivable_id INT UNSIGNED DEFAULT NULL,
  case_id INT UNSIGNED DEFAULT NULL,
  sales_id INT UNSIGNED DEFAULT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  subtotal DECIMAL(12,0) DEFAULT 0,
  tax DECIMAL(12,0) DEFAULT 0,
  discount DECIMAL(12,0) DEFAULT 0,
  total_amount DECIMAL(12,0) DEFAULT 0,
  receipt_method VARCHAR(30) DEFAULT NULL,
  invoice_category VARCHAR(50) DEFAULT NULL,
  status VARCHAR(20) DEFAULT '待收款',
  bank_ref VARCHAR(50) DEFAULT NULL,
  note TEXT,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. 收款單-合併請款明細
CREATE TABLE IF NOT EXISTS receipt_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  receipt_id INT UNSIGNED NOT NULL,
  main_case_number VARCHAR(30) DEFAULT NULL,
  merge_case_number VARCHAR(30) DEFAULT NULL,
  amount DECIMAL(12,0) DEFAULT 0,
  note VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (receipt_id) REFERENCES receipts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. 應付帳款單
CREATE TABLE IF NOT EXISTS payables (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payable_number VARCHAR(30) NOT NULL,
  create_date DATE NOT NULL,
  vendor_name VARCHAR(100) DEFAULT NULL,
  payment_period VARCHAR(30) DEFAULT NULL,
  payment_terms VARCHAR(50) DEFAULT NULL,
  subtotal DECIMAL(12,0) DEFAULT 0,
  tax DECIMAL(12,0) DEFAULT 0,
  total_amount DECIMAL(12,0) DEFAULT 0,
  prepaid DECIMAL(12,0) DEFAULT 0,
  payable_amount DECIMAL(12,0) DEFAULT 0,
  note TEXT,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. 應付帳款-分公司拆帳
CREATE TABLE IF NOT EXISTS payable_branches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payable_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  amount DECIMAL(12,0) DEFAULT 0,
  note VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. 應付帳款-發票明細
CREATE TABLE IF NOT EXISTS payable_invoices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payable_id INT UNSIGNED NOT NULL,
  invoice_date DATE DEFAULT NULL,
  invoice_number VARCHAR(30) DEFAULT NULL,
  tax_id VARCHAR(20) DEFAULT NULL,
  amount_untaxed DECIMAL(12,0) DEFAULT 0,
  tax DECIMAL(12,0) DEFAULT 0,
  subtotal DECIMAL(12,0) DEFAULT 0,
  FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. 付款單
CREATE TABLE IF NOT EXISTS payments_out (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_number VARCHAR(30) NOT NULL,
  create_date DATE NOT NULL,
  payment_date DATE DEFAULT NULL,
  payable_id INT UNSIGNED DEFAULT NULL,
  vendor_name VARCHAR(100) DEFAULT NULL,
  payment_method VARCHAR(30) DEFAULT NULL,
  payment_type VARCHAR(30) DEFAULT NULL,
  payment_terms VARCHAR(50) DEFAULT NULL,
  status VARCHAR(20) DEFAULT '待付款',
  subtotal DECIMAL(12,0) DEFAULT 0,
  tax DECIMAL(12,0) DEFAULT 0,
  remittance_fee DECIMAL(12,0) DEFAULT 0,
  total_amount DECIMAL(12,0) DEFAULT 0,
  main_category VARCHAR(50) DEFAULT NULL,
  sub_category VARCHAR(50) DEFAULT NULL,
  note TEXT,
  created_by INT UNSIGNED DEFAULT NULL,
  updated_by INT UNSIGNED DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. 付款單-分公司拆帳
CREATE TABLE IF NOT EXISTS payment_out_branches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_out_id INT UNSIGNED NOT NULL,
  branch_id INT UNSIGNED DEFAULT NULL,
  amount DECIMAL(12,0) DEFAULT 0,
  note VARCHAR(200) DEFAULT NULL,
  FOREIGN KEY (payment_out_id) REFERENCES payments_out(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. 付款單-憑證明細
CREATE TABLE IF NOT EXISTS payment_out_vouchers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  payment_out_id INT UNSIGNED NOT NULL,
  voucher_type VARCHAR(30) DEFAULT NULL,
  amount DECIMAL(12,0) DEFAULT 0,
  FOREIGN KEY (payment_out_id) REFERENCES payments_out(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
