-- Migration 051: 加大客戶相關欄位長度（防截斷）

ALTER TABLE customers MODIFY COLUMN name VARCHAR(200) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN contact_person VARCHAR(100) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN phone VARCHAR(100) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN mobile VARCHAR(100) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN site_address VARCHAR(500) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN payment_info VARCHAR(200) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN original_customer_no VARCHAR(100) DEFAULT NULL;
ALTER TABLE customers MODIFY COLUMN warranty_note VARCHAR(300) DEFAULT NULL;

ALTER TABLE customer_contacts MODIFY COLUMN contact_name VARCHAR(100) DEFAULT NULL;
ALTER TABLE customer_contacts MODIFY COLUMN phone VARCHAR(100) DEFAULT NULL;
ALTER TABLE customer_contacts MODIFY COLUMN role VARCHAR(200) DEFAULT NULL;
