-- =============================================
-- Seed: 下拉選單選項
-- =============================================

-- 客戶需求 (customer_demand)
INSERT INTO `dropdown_options` (`category`, `label`, `sort_order`) VALUES
('customer_demand', 'APP重新註冊', 1),
('customer_demand', 'LED旋轉警示燈', 2),
('customer_demand', '代安裝監控', 3),
('customer_demand', '停用不斷電系統', 4),
('customer_demand', '光纖', 5),
('customer_demand', '光纖、POE、網通、總機、電話線', 6),
('customer_demand', '大門自動倒數、安全光閘控制', 7),
('customer_demand', '對講機', 8),
('customer_demand', '對講機查修', 9),
('customer_demand', '對講機移動', 10),
('customer_demand', '廣播系統', 11),
('customer_demand', '弱電', 12),
('customer_demand', '弱電箱檢查、網路', 13),
('customer_demand', '影像對講機', 14),
('customer_demand', '拉網路線', 15),
('customer_demand', '拉網路線、電話總機', 16),
('customer_demand', '拉電話線', 17),
('customer_demand', '既有UPS 要汰換', 18),
('customer_demand', '機台作業員監視器', 19),
('customer_demand', '機櫃、網通、總機、門禁、電子鎖、網路線、電話線、電視線', 20),
('customer_demand', '汰換對講機', 21),
('customer_demand', '汰換攝影機', 22),
('customer_demand', '監控主機重新設定', 23),
('customer_demand', '監控硬碟', 24),
('customer_demand', '監視器', 25),
('customer_demand', '監視器、光纖', 26),
('customer_demand', '監視器、光纖、機櫃、網路線、電話線、電視線、NCC送審', 27),
('customer_demand', '監視器、廣播、總機', 28),
('customer_demand', '監視器、拉網路線', 29),
('customer_demand', '監視器、捲門控制器', 30),
('customer_demand', '監視器、網路', 31),
('customer_demand', '監視器、網路、捲門控制器', 32),
('customer_demand', '監視器、網路、線路、弱電箱、門鈴、總機', 33),
('customer_demand', '監視器、網路、門禁', 34),
('customer_demand', '監視器、網路、電話系統', 35),
('customer_demand', '監視器、網路佈線、弱電箱整理', 36),
('customer_demand', '監視器、網通、總機', 37),
('customer_demand', '監視器、總機話機', 38),
('customer_demand', '監視器、門禁、電話系統', 39),
('customer_demand', '監視器、音響系統', 40),
('customer_demand', '監視器主機', 41),
('customer_demand', '監視器拆除', 42),
('customer_demand', '監視器汰換', 43),
('customer_demand', '監視器沒收音', 44),
('customer_demand', '監視器移機', 45),
('customer_demand', '網路', 46),
('customer_demand', '網路佈線', 47),
('customer_demand', '網路強波器', 48),
('customer_demand', '網路線', 49),
('customer_demand', '網路線、分享器', 50),
('customer_demand', '網路線重拉', 51),
('customer_demand', '總機汰換', 52),
('customer_demand', '總機話機', 53),
('customer_demand', '車道警示燈', 54),
('customer_demand', '遠端I/O', 55),
('customer_demand', '門禁', 56),
('customer_demand', '門禁、網路、總機', 57),
('customer_demand', '門禁、電子鎖', 58),
('customer_demand', '電子鎖', 59),
('customer_demand', '電話總機', 60);

-- 系統別 (system_type)
INSERT INTO `dropdown_options` (`category`, `label`, `sort_order`) VALUES
('system_type', '不斷電系統', 1),
('system_type', '光纖系統相關', 2),
('system_type', '其他需求', 3),
('system_type', '多系統', 4),
('system_type', '對講系統相關', 5),
('system_type', '廣播系統相關', 6),
('system_type', '弱電整合規劃', 7),
('system_type', '捲門衛士,控制相關', 8),
('system_type', '新客戶查修,移機,追加,代安裝', 9),
('system_type', '監視+網路', 10),
('system_type', '監視+總機', 11),
('system_type', '監視+門禁+網路', 12),
('system_type', '監視系統相關', 13),
('system_type', '網路系統相關', 14),
('system_type', '線路相關', 15),
('system_type', '老客戶查修,移機,追加,更換', 16),
('system_type', '門禁系統相關', 17),
('system_type', '電子鎖', 18),
('system_type', '電話總機系統相關', 19);

-- 訂金支付方式 (deposit_method)
INSERT INTO `dropdown_options` (`category`, `label`, `sort_order`) VALUES
('deposit_method', '現金', 1),
('deposit_method', '匯款', 2),
('deposit_method', '支票', 3);
